// components
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";

// styling
import "@/styles/globals.css";

// meta
export const metadata = {
  title: "Dronans Wedding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased grid min-h-screen grid-rows-1">
        <Navbar />
        <main className="pt-16">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
